"""Add UserLessonCompletion table for progress tracking

Revision ID: 1ae4db516a0c
Revises: 1f4f555ebfb3
Create Date: 2025-09-08 17:09:27.817745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae4db516a0c'
down_revision: Union[str, Sequence[str], None] = '1f4f555ebfb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
