"""Add user_lesson_completions table

Revision ID: 1f4f555ebfb3
Revises: 2b9830b819f2
Create Date: 2025-09-08 17:01:46.263405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4f555ebfb3'
down_revision: Union[str, Sequence[str], None] = '2b9830b819f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
