"""add news sources table

Revision ID: 2b9830b819f2
Revises: 94bffda86309
Create Date: 2025-09-02 10:46:49.932635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9830b819f2'
down_revision: Union[str, Sequence[str], None] = '94bffda86309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sources_id'), 'news_sources', ['id'], unique=False)
    op.create_index(op.f('ix_news_sources_url'), 'news_sources', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sources_url'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_id'), table_name='news_sources')
    op.drop_table('news_sources')
    # ### end Alembic commands ###
