"""Add attachment_url to lessons table

Revision ID: f6e1858bd094
Revises: 3aacff46beda
Create Date: 2025-09-01 20:00:15.129906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e1858bd094'
down_revision: Union[str, Sequence[str], None] = '3aacff46beda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('attachment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'attachment_url')
    # ### end Alembic commands ###
